// Copies the Phosphor icons the app uses into src/app/shared/ui/icon/icons.generated.ts,
// so <app-icon> can draw them inline without loading anything at runtime.
//
// To add an icon: put its name below (see https://phosphoricons.com), then run
//   node scripts/generate-icons.mjs
// Add ":duotone" (or ":fill") to a name for that weight instead of the regular one.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ICONS = [
  'arrow-counter-clockwise', 'arrow-left', 'arrow-right', 'arrow-square-out', 'arrow-up-right',
  'briefcase', 'buildings', 'cake', 'calendar-blank', 'calendar-check', 'camera', 'caret-down',
  'caret-left', 'caret-right', 'certificate', 'chalkboard-teacher', 'chat-circle-text', 'check',
  'check-circle', 'circle-notch', 'clipboard-text', 'clock', 'cloud-arrow-up', 'confetti',
  'dots-three-vertical', 'download-simple', 'envelope-simple', 'eye', 'file-pdf', 'file-text',
  'floppy-disk', 'funnel-simple', 'graduation-cap', 'hourglass', 'identification-card', 'info',
  'key', 'list', 'list-checks', 'lock-simple', 'magnifying-glass', 'map-pin', 'medal', 'minus',
  'note-pencil', 'notebook', 'paper-plane-tilt', 'pencil-simple', 'phone', 'plus', 'seal-check',
  'sign-in', 'sign-out', 'squares-four', 'timer', 'trash', 'user', 'user-circle', 'users-three',
  'warning', 'warning-circle', 'x', 'x-circle', 'upload-simple', 'file-arrow-up', 'play', 'stop',
  'image', 'chats-circle', 'hand-waving', 'link', 'chart-bar', 'caret-up-down', 'copy', 'user-plus',
  'tray', 'arrow-clockwise', 'student', 'clock-countdown',
  // Larger illustrations for empty states.
  'buildings:duotone', 'chalkboard-teacher:duotone', 'clipboard-text:duotone', 'clock:duotone',
  'confetti:duotone', 'envelope-simple:duotone', 'files:duotone', 'lock-simple:duotone',
  'note-pencil:duotone', 'notebook:duotone', 'users-three:duotone', 'chat-circle-text:duotone',
  'seal-check:duotone', 'link-break:duotone', 'chart-bar:duotone', 'tray:duotone', 'student:duotone',
  'user-plus:duotone',
];

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const assets = join(root, 'node_modules', '@phosphor-icons', 'core', 'assets');

function load(entry) {
  const [name, weight = 'regular'] = entry.split(':');
  const file = weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`;
  const svg = readFileSync(join(assets, weight, file), 'utf8');

  const body = svg.replace(/^<svg[^>]*>|<\/svg>\s*$/g, '');
  const elements = body.match(/<[a-z]+\b[^>]*>/g) ?? [];
  return elements.map((element) => {
    if (!element.startsWith('<path')) {
      throw new Error(`${entry}: <${element.slice(1).split(/\s/)[0]}> is not supported, only <path>.`);
    }
    const d = element.match(/\sd="([^"]+)"/)?.[1];
    const opacity = element.match(/\sopacity="([^"]+)"/)?.[1];
    if (!d) {
      throw new Error(`${entry}: a <path> has no d attribute.`);
    }
    return opacity ? { d, o: Number(opacity) } : { d };
  });
}

const lines = [...new Set(ICONS)].sort().map((entry) => `  '${entry}': ${JSON.stringify(load(entry))},`);

writeFileSync(
  join(root, 'src', 'app', 'shared', 'ui', 'icon', 'icons.generated.ts'),
  `// Generated by scripts/generate-icons.mjs from Phosphor Icons (MIT licence). Do not edit.

export interface IconPath {
  d: string;
  /** Opacity of the background shape in duotone icons. */
  o?: number;
}

export const ICONS = {
${lines.join('\n')}
} satisfies Record<string, IconPath[]>;

export type IconName = keyof typeof ICONS;
`,
);

console.log(`Wrote ${lines.length} icons.`);
